### ISSUE TITLE
Error when downloading user creds for Postgres

### ISSUE THREAD

**Issue by lazee** [aiven/aiven-client#121]
aiven client version: 2.2.3

When running command

`avn service user-creds-download --project my-project my-pg-service --username myusername`

I get the error

```
Traceback (most recent call last):
  File "/usr/local/bin/avn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aiven/client/__main__.py", line 5, in main
    AivenCLI().main()
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 262, in main
    sys.exit(self.run())
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 234, in run
    return self.run_actual(args)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 256, in run_actual
    return func()  # pylint: disable=not-callable
  File "/usr/local/lib/python3.7/site-packages/aiven/client/cli.py", line 789, in service__user_creds_download
    fp.write(user["access_cert"])
KeyError: 'access_cert'
```

**Comment by lazee** [comment]
Just discovered 

`avn service ca get --project myproject --target-filepath ./` 

Maybe a better error message in the above command?

AND: Isn't there a way to get a user password from the client?
