### ISSUE TITLE
v.2.5.0: `integration-endpoint-types-list` and `integration-types-list` throw errors

### ISSUE THREAD

**Issue by georgecrawford** [aiven/aiven-client#153]
```
$ avn --version
aiven-client 2.5.0

$ avn service integration-endpoint-types-list
Traceback (most recent call last):
  File "/usr/local/bin/avn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aiven/client/__main__.py", line 5, in main
    AivenCLI().main()
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 296, in main
    sys.exit(self.run())
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 268, in run
    return self.run_actual(args)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 290, in run_actual
    return func()  # pylint: disable=not-callable
  File "/usr/local/lib/python3.7/site-packages/aiven/client/cli.py", line 1324, in service__integration_endpoint_types_list
    endpoint_types = self.client.get_service_integration_endpoint_types(self.args.project)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/client.py", line 303, in get_service_integration_endpoint_types
    path = self.build_path("project", project, "integration_endpoint_types")
  File "/usr/local/lib/python3.7/site-packages/aiven/client/client.py", line 167, in build_path
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/client.py", line 167, in <genexpr>
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 834, in quote
    return quote_from_bytes(string, safe)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

$ avn service integration-types-list
Traceback (most recent call last):
  File "/usr/local/bin/avn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/aiven/client/__main__.py", line 5, in main
    AivenCLI().main()
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 296, in main
    sys.exit(self.run())
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 268, in run
    return self.run_actual(args)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/argx.py", line 290, in run_actual
    return func()  # pylint: disable=not-callable
  File "/usr/local/lib/python3.7/site-packages/aiven/client/cli.py", line 1410, in service__integration_types_list
    endpoint_types = self.client.get_service_integration_types(self.args.project)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/client.py", line 337, in get_service_integration_types
    path = self.build_path("project", project, "integration_types")
  File "/usr/local/lib/python3.7/site-packages/aiven/client/client.py", line 167, in build_path
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/usr/local/lib/python3.7/site-packages/aiven/client/client.py", line 167, in <genexpr>
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 834, in quote
    return quote_from_bytes(string, safe)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Comment by lornajane** [comment]
Looks like this happens because the underlying endpoint expects to get the project name, and it's not a required parameter for this command. Supply `--project [name]` and the project you want to list integrations for (see `avn project list`) to get the command to work. We can also update the command to know the flag is required rather than producing the error.

**Comment by georgecrawford** [comment]
Yep, that's the problem. Thanks @lornajane. If you could add that as a required param, it'd be more user friendly!

**Comment by lornajane** [comment]
No problem at all, it's #173
