### ISSUE TITLE
Service database username avnadmin does not exist status 403

### ISSUE THREAD

**Issue by allen-munsch** [aiven/aiven-client#217]
# What happened?

- pools are not being created
- Service database username avnadmin does not exist","status":403

```
avn --auth-token "###" service connection-pool-create asdf-pr-3586 --project asdf-review-apps --dbname defaultdb --username avnadmin --pool-name asdf-pool --pool-size 50 --json 

ERROR	command failed: Error: {"errors":

[{"message":"Service database username avnadmin does not exist","status":403}],"message":"Service database username avnadmin does not exist"}

Traceback (most recent call last):
  File "/app/.heroku/python/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/app/.heroku/python/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/app/.heroku/python/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/app/.heroku/python/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/app/.heroku/python/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/tmp/codon/tmp/buildpacks/47e2e265d630dfd66344f130d506a6039afb0919/bin/tasks.py", line 368, in create_pool_uri_and_set_env
    pool_uri = create_pool(config)
  File "/tmp/codon/tmp/buildpacks/47e2e265d630dfd66344f130d506a6039afb0919/bin/tasks.py", line 203, in create_pool
    do_popen(pool_create_cmd(**config), err_msg="Failed to create pool.")
  File "/tmp/codon/tmp/buildpacks/47e2e265d630dfd66344f130d506a6039afb0919/bin/tasks.py", line 132, in do_popen
    raise exc(err_msg)
Exception: Failed to create pool.
```

# What did you expect to happen?

Pool to get created

# What else do we need to know?

- https://github.com/Property-Meld/heroku-buildpack-aiven-deploy-pg
- https://github.com/Property-Meld/heroku-buildpack-aiven-deploy-pg/blob/master/bin/tasks.py#L30 
- https://github.com/Property-Meld/heroku-buildpack-aiven-deploy-pg/blob/master/bin/tasks.py#L203

**Comment by rikonen** [comment]
This looks to be an issue on backend side that affects a subset of services, I'll have a look

**Comment by rikonen** [comment]
This should be fixed now. Please reopen if this still reproduces
