### ISSUE TITLE
Error quote_from_bytes()

### ISSUE THREAD

**Issue by aronneagu** [aiven/aiven-client#246]
# What happened?
Ran the following command and got the error
`avn --auth-token $AIVEN_USER_TOKEN service list`
```
Traceback (most recent call last):
  File "/usr/bin/avn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/aiven/client/__main__.py", line 5, in main
    AivenCLI().main()
  File "/usr/lib/python3.8/site-packages/aiven/client/argx.py", line 309, in main
    sys.exit(self.run(args))
  File "/usr/lib/python3.8/site-packages/aiven/client/argx.py", line 281, in run
    return self.run_actual(args)
  File "/usr/lib/python3.8/site-packages/aiven/client/argx.py", line 303, in run_actual
    return func()  # pylint: disable=not-callable
  File "/usr/lib/python3.8/site-packages/aiven/client/cli.py", line 966, in service__list
    services = self.client.get_services(project=self.get_project())
  File "/usr/lib/python3.8/site-packages/aiven/client/client.py", line 1546, in get_services
    self.build_path("project", project, "service"),
  File "/usr/lib/python3.8/site-packages/aiven/client/client.py", line 168, in build_path
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/usr/lib/python3.8/site-packages/aiven/client/client.py", line 168, in <genexpr>
    return "/" + "/".join(quote(part, safe="") for part in parts)
  File "/usr/lib/python3.8/urllib/parse.py", line 851, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.8/urllib/parse.py", line 876, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

# What did you expect to happen?
A list of all services

# What else do we need to know?
This command fails on the following system: Alpine Linux 3.12.0
```
> python3 --version
Python 3.8.10
> avn --version
aiven-client 2.14.4
```

This command run successfully on Ubuntu 20.04, with same version of python3 and aiven-client

**Comment by rominf** [comment]
Hello, @aronneagu.

Thanks for your issue. This is indeed a bug (if `--auth-token` is a documented option that comes before the command, then it should work).

If you don't mind storing tokens in a special file, I recommend you to follow these instructions: https://github.com/aiven/aiven-client#authenticate-logins-and-tokens

I am looking forward to hearing from you, whether it works for you!

**Comment by rominf** [comment]
Another solution is to provide `--project` argument:
```
avn --auth-token $AIVEN_USER_TOKEN service list --project $AIVEN_PROJECT
```

**Comment by aronneagu** [comment]
Adding the `--project <project_name>` did help. Thank you
