### ISSUE TITLE
issue printing logs with non-ascii characters

### ISSUE THREAD

**Issue by contra** [aiven/aiven-client#83]
```Traceback (most recent call last):
  File "/usr/local/bin/avn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/aiven/client/__main__.py", line 5, in main
    AivenCLI().main()
  File "/usr/local/lib/python2.7/site-packages/aiven/client/argx.py", line 246, in main
    sys.exit(self.run())
  File "/usr/local/lib/python2.7/site-packages/aiven/client/argx.py", line 223, in run
    return self.run_actual(args)
  File "/usr/local/lib/python2.7/site-packages/aiven/client/argx.py", line 240, in run_actual
    return func()  # pylint: disable=not-callable
  File "/usr/local/lib/python2.7/site-packages/aiven/client/cli.py", line 245, in service_logs
    new_offset = self._show_logs(msgs)
  File "/usr/local/lib/python2.7/site-packages/aiven/client/cli.py", line 213, in _show_logs
    print("{time:<27}{hostname} {unit} {msg}".format(**log_msg))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0130' in position 452: ordinal not in range(128)
```

Character it blows up on: https://www.fileformat.info/info/unicode/char/0130/index.htm

**Comment by rikonen** [comment]
As a workaround using Python 3.6 is likely to fix the problem.

**Comment by rominf** [comment]
Python 2.7 is no longer supported; please use Python 3 instead. If the problem persists, please reopen the ticket.
